export const FESTIVAL_FILTER_LANGUAGES = [
  "kor",
  "eng",
  "jpn",
  "chn",
  "fra",
  "spa",
  "rus",
] as const;

export type FestivalFilterLanguage = (typeof FESTIVAL_FILTER_LANGUAGES)[number];

export const FESTIVAL_KEYWORD_IDS = [
  "spring",
  "summer",
  "autumn",
  "winter",
  "traditional",
  "experience",
  "performance",
  "food",
  "fireworks",
  "lantern",
  "cherryBlossom",
  "nightView",
  "seoul",
  "busan",
  "jeju",
  "gangwon",
] as const;

export type FestivalKeywordId = (typeof FESTIVAL_KEYWORD_IDS)[number];

export type FestivalKeywordLabels = Record<FestivalKeywordId, string>;

export const FESTIVAL_FILTER_KEYWORDS = {
  kor: {
    spring: "봄",
    summer: "여름",
    autumn: "가을",
    winter: "겨울",
    traditional: "전통",
    experience: "체험",
    performance: "공연",
    food: "음식",
    fireworks: "불꽃",
    lantern: "등불",
    cherryBlossom: "벚꽃",
    nightView: "야경",
    seoul: "서울",
    busan: "부산",
    jeju: "제주도",
    gangwon: "강원도",
  },
  eng: {
    spring: "Spring",
    summer: "Summer",
    autumn: "Autumn",
    winter: "Winter",
    traditional: "Traditional",
    experience: "Experience",
    performance: "Performance",
    food: "Food",
    fireworks: "Fireworks",
    lantern: "Lantern",
    cherryBlossom: "Cherry Blossom",
    nightView: "Night View",
    seoul: "Seoul",
    busan: "Busan",
    jeju: "Jeju",
    gangwon: "Gangwon",
  },
  jpn: {
    spring: "春",
    summer: "夏",
    autumn: "秋",
    winter: "冬",
    traditional: "伝統",
    experience: "体験",
    performance: "公演",
    food: "グルメ",
    fireworks: "花火",
    lantern: "提灯",
    cherryBlossom: "桜",
    nightView: "夜景",
    seoul: "ソウル",
    busan: "釜山",
    jeju: "済州島",
    gangwon: "江原道",
  },
  chn: {
    spring: "春",
    summer: "夏",
    autumn: "秋",
    winter: "冬",
    traditional: "传统",
    experience: "体验",
    performance: "表演",
    food: "美食",
    fireworks: "烟花",
    lantern: "灯笼",
    cherryBlossom: "樱花",
    nightView: "夜景",
    seoul: "首尔",
    busan: "釜山",
    jeju: "济州岛",
    gangwon: "江原道",
  },
  fra: {
    spring: "Printemps",
    summer: "Été",
    autumn: "Automne",
    winter: "Hiver",
    traditional: "Tradition",
    experience: "Expérience",
    performance: "Spectacle",
    food: "Gastronomie",
    fireworks: "Feux d'artifice",
    lantern: "Lanternes",
    cherryBlossom: "Cerisiers",
    nightView: "Paysage nocturne",
    seoul: "Séoul",
    busan: "Busan",
    jeju: "Jeju",
    gangwon: "Gangwon",
  },
  spa: {
    spring: "Primavera",
    summer: "Verano",
    autumn: "Otoño",
    winter: "Invierno",
    traditional: "Tradición",
    experience: "Experiencia",
    performance: "Espectáculo",
    food: "Gastronomía",
    fireworks: "Fuegos artificiales",
    lantern: "Faroles",
    cherryBlossom: "Cerezos",
    nightView: "Paisaje nocturno",
    seoul: "Seúl",
    busan: "Busan",
    jeju: "Jeju",
    gangwon: "Gangwon",
  },
  rus: {
    spring: "Весна",
    summer: "Лето",
    autumn: "Осень",
    winter: "Зима",
    traditional: "Традиция",
    experience: "Опыт",
    performance: "Шоу",
    food: "Еда",
    fireworks: "Фейерверк",
    lantern: "Фонарь",
    cherryBlossom: "Сакура",
    nightView: "Ночной пейзаж",
    seoul: "Сеул",
    busan: "Пусан",
    jeju: "Чеджу",
    gangwon: "Канвондо",
  },
} satisfies Record<FestivalFilterLanguage, FestivalKeywordLabels>;
